model_provider = "claudecn"
model = "gpt-5.5"
model_reasoning_effort = "high"
disable_response_storage = true


[model_providers.claudecn]
name = "claudecn"
base_url = "https://claudecn.top/v1"
wire_api = "responses"
requires_openai_auth = true
